name: anime_player
description: "A new Flutter project."

publish_to: "none"

version: 1.0.2+3

environment:
  sdk: ^3.7.0

dependencies:
  cupertino_icons: ^1.0.8
  flutter:
    sdk: flutter
  flutter_native_splash: ^2.4.5
  flutter_slidable: ^4.0.0
  get: ^4.7.2
  share_plus: ^10.1.4
  shared_preferences: ^2.5.2
  webview_flutter: ^4.10.0

dev_dependencies:
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter
  package_rename: ^1.9.0

flutter:
  uses-material-design: true

  assets:
    - assets/
